---
apiVersion: v1    
kind: Secret
metadata:
  name: appointment-secret
type: Opaque
data:
  MYSQL_DATABASE: bmFjdG8= #nacto
  MYSQL_USER: cm9vdA== #root
  MYSQL_PASSWORD: cGFzc3dvcmQ= #password
---
apiVersion: extensions/v1
kind: Deployment
metadata:
  name: appointment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: appointment
    spec:
      containers:
        - name: appointment
          image: 'neethirocks/appointment:1.0'
          ports:
            - containerPort: 80
        - env:
          - name: spring_jpa_database
            value: mysql
          - name: spring_datasource_url
            value: jdbc:mysql://mysql-master:3306/test?useSSL=false
          - name: spring_datasource_username
            valueFrom:
              secretKeyRef:
                name: appointment-secret
                key: MYSQL_USER
          - name: spring_datasource_password
            valueFrom:
              secretKeyRef:
                name: appointment-secret
                key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  labels:
    name: appointment-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: '8080'
  selector:
    app: appointment
  type: NodePort