apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment
  namespace: healthapp
spec:
  selector:
      matchLabels:
        app: appointment
  replicas: 1
  template:
    metadata:
      labels:
        app: appointment
    spec:
      containers:         
        - name: appointment
          image: 'neethirocks/appointment:1.0'          
          ports:
            - containerPort: 80
          env:
          - name: spring_jpa_database
            value: mysql
          - name: spring_datasource_url
            value: jdbc:mysql://healthdb:3306/test?createDatabaseIfNotExist=true&useSSL=false
          - name: spring_datasource_username
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
          - name: spring_datasource_password
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  labels:
    name: appointment-service
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: '8080'
  selector:
    app: appointment
  type: NodePort
