apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacto-db
  namespace: mysql-repl
spec:
  selector:
    matchLabels:
      app: nacto-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nacto-db
    spec:
      containers:
      - image: mysql:5.7
        name: nacto-db
        env:
        - name: MYSQL_SERVER_CONTAINER
          value: mysql
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
          name: nacto-db
---
apiVersion: v1
kind: Service
metadata:
  name: nacto-db
spec:
  type: NodePort
  ports:
  - name: nacto-db
    port: 3306
    targetPort: 3306
    protocol: TCP
    nodePort: 32000
  selector:
    app: nacto-db
