apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient
  namespace: mysql-repl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:         
        - image: 'neethirocks/patient:1.0'
          name: patient
          ports:
            - containerPort: 80
        - env:
          - name: spring_jpa_database
            value: mysql
          - name: spring_datasource_url
            value: jdbc:mysql://nacto-db:3306/nacto?createDatabaseIfNotExist=true&useSSL=false
          - name: spring_datasource_username
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
          - name: spring_datasource_password
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  labels:
    name: patient-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: '8080'
  selector:
    app: patient
  type: NodePort
